// Generated by https://quicktype.io

export interface MitraData {
  id: string;
  name: string;
  address: string;
  closeTime: string;
  openTime: string;
  coordinate: Coordinate;
  phoneNumber: string;
}

export interface Coordinate {
  lat: number;
  long: number;
}
