// Generated by https://quicktype.io

export interface MitraData {
    id:          number;
    name:        string;
    address:     string;
    closeHour:   string;
    openHour:    string;
    coordinate:  Coordinate;
    phoneNumber: string;
}

export interface Coordinate {
    lat:  number;
    long: number;
}
